export const endpoints = [
    { name: 'AI Image Editor', method: 'POST', path: '/api/ai-image/edit-image', type: 'multipart', params: ['media', 'prompt'], status: 'confirmed-200' },
    { name: 'Hanime Trending', method: 'GET', path: '/api/anime-hen/hanime/trending', type: 'json-or-media', params: [], status: 'confirmed-200' },
    { name: 'HentaiTV Genres', method: 'GET', path: '/api/anime-hen/hentaitv/genres', type: 'json-or-media', params: [], status: 'confirmed-200' },
    { name: 'HentaiTV Trending', method: 'GET', path: '/api/anime-hen/hentaitv/trending', type: 'json-or-media', params: [], status: 'confirmed-200' },
    { name: 'Asupan Bocil', method: 'GET', path: '/api/asupan/bocil', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Asupan Gheayubi', method: 'GET', path: '/api/asupan/gheayubi', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Asupan Kayes', method: 'GET', path: '/api/asupan/kayes', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Asupan Notnot', method: 'GET', path: '/api/asupan/notnot', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Asupan Panrika', method: 'GET', path: '/api/asupan/panrika', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Asupan Santuy', method: 'GET', path: '/api/asupan/santuy', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Asupan Tiktokgirl', method: 'GET', path: '/api/asupan/tiktokgirl', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Asupan Ukhty', method: 'GET', path: '/api/asupan/ukhty', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Fake FF Duo', method: 'GET', path: '/api/canvas/ffduo', type: 'media', params: ['user1', 'user2', 'template'], status: 'confirmed-200' },
    { name: 'Fake FF Girl', method: 'GET', path: '/api/canvas/ffgirl', type: 'media', params: ['username', 'template'], status: 'confirmed-200' },
    { name: 'Fake FF Lobby', method: 'GET', path: '/api/canvas/fake-ff', type: 'media', params: ['username', 'lobby'], status: 'confirmed-200' },
    { name: 'Fake GoPay', method: 'GET', path: '/api/canvas/fake-gopay', type: 'media', params: ['saldo', 'koin', 'terpakai', 'bulan'], status: 'confirmed-200' },
    { name: 'Fake Mobile Legends', method: 'GET', path: '/api/canvas/fake-ml', type: 'media', params: ['avatar', 'username', 'rank', 'border'], status: 'confirmed-200' },
    { name: 'Fake NGL', method: 'GET', path: '/api/canvas/fake-ngl', type: 'media', params: ['text'], status: 'confirmed-200' },
    { name: 'Fake OVO', method: 'GET', path: '/api/canvas/fake-ovo', type: 'media', params: ['saldo'], status: 'confirmed-200' },
    { name: 'Fake Pak Ustadz', method: 'GET', path: '/api/canvas/pak-ustadz', type: 'media', params: ['text'], status: 'confirmed-200' },
    { name: 'Goodbye Card', method: 'POST', path: '/api/canvas/goodbye', type: 'multipart', params: ['pp', 'avatar', 'image', 'file', 'media', 'background', 'bg', 'name', 'group', 'member'], status: 'confirmed-200' },
    { name: 'WhatsApp Quote Card', method: 'POST', path: '/api/canvas/qcwa', type: 'multipart', params: ['avatar', 'text', 'username', 'phone', 'tag', 'mode'], status: 'confirmed-200' },
    { name: 'Cecan China', method: 'GET', path: '/api/cecan/China', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Hijaber', method: 'GET', path: '/api/cecan/Hijaber', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Indonesia', method: 'GET', path: '/api/cecan/Indonesia', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Japan', method: 'GET', path: '/api/cecan/Japan', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Jiso', method: 'GET', path: '/api/cecan/Jiso', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Justinaxie', method: 'GET', path: '/api/cecan/Justinaxie', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Korea', method: 'GET', path: '/api/cecan/Korea', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Malaysia', method: 'GET', path: '/api/cecan/Malaysia', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Rose', method: 'GET', path: '/api/cecan/Rose', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Ryujin', method: 'GET', path: '/api/cecan/Ryujin', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Thailand', method: 'GET', path: '/api/cecan/Thailand', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Cecan Vietnam', method: 'GET', path: '/api/cecan/Vietnam', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Facebook Downloader', method: 'GET', path: '/api/download/facebook', type: 'json-or-media', params: ['url'], status: 'confirmed-200' },
    { name: 'GitHub Downloader', method: 'GET', path: '/api/download/github', type: 'json-or-media', params: ['repo', 'ref'], status: 'confirmed-200' },
    { name: 'Instagram Downloader', method: 'GET', path: '/api/download/instagram', type: 'json-or-media', params: ['url'], status: 'confirmed-200' },
    { name: 'TikTok Downloader', method: 'GET', path: '/api/download/tiktok', type: 'json-or-media', params: ['url'], status: 'confirmed-200' },
    { name: 'Asmaul Husna', method: 'GET', path: '/api/islamic/asmaul-husna', type: 'json-or-media', params: ['nomor'], status: 'confirmed-200' },
    { name: 'Ayat Kursi', method: 'GET', path: '/api/islamic/ayat-kursi', type: 'json-or-media', params: [], status: 'confirmed-200' },
    { name: 'Bacaan Sholat', method: 'GET', path: '/api/islamic/bacaan-sholat', type: 'json-or-media', params: [], status: 'confirmed-200' },
    { name: 'Jadwal Sholat', method: 'GET', path: '/api/islamic/jadwal-sholat', type: 'json-or-media', params: ['wilayah'], status: 'confirmed-200' },
    { name: 'Kisah Nabi', method: 'GET', path: '/api/islamic/kisah-nabi', type: 'json-or-media', params: ['nama'], status: 'confirmed-200' },
    { name: 'Niat Sholat', method: 'GET', path: '/api/islamic/niat-sholat', type: 'json-or-media', params: ['waktu'], status: 'confirmed-200' },
    { name: 'Tafsir', method: 'GET', path: '/api/islamic/tafsir', type: 'json-or-media', params: ['query'], status: 'confirmed-200' },
    { name: 'Random Andin', method: 'GET', path: '/api/random/andin', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Random Seegore', method: 'GET', path: '/api/random/seegore', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'Random Tobrut', method: 'GET', path: '/api/random/tobrut', type: 'media', params: [], status: 'confirmed-200' },
    { name: 'User Profile', method: 'GET', path: '/api/user/profile', type: 'json-or-media', params: [], status: 'confirmed-200' },
    { name: 'Renew Membership', method: 'POST', path: '/api/user/renew', type: 'json', params: ['role', 'days', 'couponCode', 'trx_id', 'trxId'], status: 'confirmed-200' },
    { name: 'User Stats', method: 'GET', path: '/api/user/stats', type: 'json-or-media', params: [], status: 'confirmed-200' }
]

if (endpoints.length !== 51) {
    throw new Error(`Expected 51 endpoints, got ${endpoints.length}`)
}